### ISSUE TITLE
Week 1 - Core Idea, Initial Research, and Environment Set Up

### ISSUE THREAD

**Issue by theoliviawales** [TeamMoodGitHub/Aaron-Term-1#1]
This week will revolve around getting up to speed in Node.js and React. Focus on going through the documentation pages for each and try to make a few demo pages to get set up! I would try and follow a guide online that uses both React and Node. [This one](https://scotch.io/tutorials/react-on-the-server-for-beginners-build-a-universal-react-and-node-app) looks pretty good.

You don't need to look into using any databases yet, but if you find that you are getting curious, look into NoSQL vs. SQL. [This article](http://www.monitis.com/blog/cc-in-review-the-key-differences-between-sql-and-nosql-dbs/) goes over some advantages and disadvantages of each.

If you feel up to it, create something as basic as your main home page that features the text box and two buttons. You can wire up the buttons to bring you to a different page, but the pages can be empty for now.

Next week we will focus on getting the necessary data for your project. By then, we should have a better idea on what exactly we'll need.

If you can get the simple pages completed this week, I'd love to see the code in this repo and see the pages up and running :)

**Comment by nbdaaron** [comment]
This week, I spent a chunk of time familiarizing myself with React and going over the concepts for Node.js Express servers. I'm planning to host an Express site that will serve as an API for the website's requests. The site will route all other requests to the compiled React site. 

The basic layout for the homepage has been completed in React, so the following week, I will be spending time putting together the Express server, setting it up to host on Heroku, and deciding on a database to use to store all the retrieved data. 😄
