### ISSUE TITLE
Week 2 - Beginning back-end, acquiring data, researching DBs

### ISSUE THREAD

**Issue by theoliviawales** [TeamMoodGitHub/Aaron-Term-1#2]
Last week was a nice introduction into Node and React. While still learning the ins and outs of these tools, you should look at how you are going to acquire the data you need on LoL jungle strategies and other necessary champ details. With the data on your mind, you'll know how to properly layout the back-end tech.

Look into some cheap/free database options that you can use for your project. I obviously have to shill for AWS and push DynamoDB on you if you are still looking into using a NoSQL option. You mentioned that you know some free MongoDB options which would be very useful.

If you are able to get a dummy database going, try and work to show the database data on a simple webpage just to verify that you can access the data and render it to the screen.

Good luck this week! Enjoy your last week at your job as well :)

**Comment by nbdaaron** [comment]
This week, I spent a good chunk of time setting up my backend. I've decided to use Mongo as my database, and I created and linked an express server to my react front-end. I've also started pulling data from Riot's API and storing it into Mongo to have sample data to display on the website.

My current challenge is to find a good way to scrape game data from Riot's API - they don't provide compiled statistics with champion win rates for users so I need to go through games myself to calculate whatever values I need. Although this may not be as important as the main site itself, it may be a better idea to start working on this now so I can have a program continuously scraping game data while I work on other components of the site. (The scraper can't be too fast anyways, as Riot's API limits are pretty small for applications under development).

This next week, I plan to spend a bit of time looking into different methods of scraping game data from the API, and I'll finish laying out the structure of the main site (and possibly work on some styling as well). I'll discuss this a bit more with you, Richie, before starting though so I can get some of your input! 👍
